apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kellnr.fullname" . }}
  labels:
    {{- include "kellnr.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kellnr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kellnr.selectorLabels" . | nindent 8 }}
    spec:
      {{- if or .Values.pvc.enabled .Values.importCert.enabled }}
      volumes:
      {{- end }}
        {{- if .Values.pvc.enabled }}
        - name: {{ .Values.deployment.volumes.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.deployment.volumes.persistentVolumeClaim }}
        {{- end }}
        {{- if .Values.importCert.enabled }}
        - name: {{ .Values.importCert.volumeName | quote }}
          configMap:
            name: {{ .Values.importCert.configMapName | quote }}
        {{- end }}
     
        {{- if .Values.dns.enabled }}
      dnsPolicy: {{ .Values.dns.dnsPolicy | quote }}
      dnsConfig:
        nameservers:
          {{- toYaml .Values.dns.dnsConfig.nameservers | nindent 12 }}
        searches:
          {{- toYaml .Values.dns.dnsConfig.searches | nindent 12 }}
      {{- end }}

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kellnr.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- if eq .Values.kellnr.log.level "debug" }}
          - name: RUST_BACKTRACE
            value: "1"
          {{- end }}
          {{- if .Values.extraEnv }}
          {{- toYaml .Values.extraEnv | indent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name | quote }}
          ports:
            - containerPort: {{ .Values.service.api.port }}
              name: kellnr-api
              protocol: TCP
          {{- if or .Values.pvc.enabled .Values.importCert.enabled }}
          volumeMounts:
          {{- end }}
            {{- if .Values.pvc.enabled }}
            - mountPath: {{ .Values.kellnr.registry.dataDir | quote }}
              name: {{ .Values.deployment.volumes.name }}
            {{- end }}
            {{- if .Values.importCert.enabled }}
            - name: {{ .Values.importCert.volumeName }}
              mountPath: "{{ .Values.kellnr.registry.dataDir }}/cert"
              readOnly: true
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
